### ISSUE TITLE
Problem between conda & pip?

### ISSUE THREAD

**Issue by niko2020** [luandev/ComfyUI-CrewAI#8]
[!] ERROR: Invalid requirement: 'typing-extensions=4.12.1=pypi_0'
[!] Hint: = is not a valid operator. Did you mean == ?
install script failed: https://github.com/luandev/ComfyUI-CrewAI

Nice project
Cheers

**Comment by luandev** [comment]
Hey thanks for reporting this to me I will be looking into it! 👍🏽

**Comment by luandev** [comment]
@niko2020 I pushed some changes, but haven't managed to test in isolation yet if you could please have a look and see if it works on your side
